version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=profilsearch_root
      - POSTGRES_PASSWORD=pipou
      - POSTGRES_DB=profilsearch
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080

volumes:
  db:
    driver: local